<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="brandons-mbp.lan" ignored="0" name="Default test" tests="14" failures="1" timestamp="19 Jan 2018 17:43:38 GMT" time="0.059" errors="0">
  <testcase name="LoginFailure" time="0.009" classname="webLogin.CouncelorLogin"/>
  <testcase name="LoginSuccess" time="0.001" classname="webLogin.CouncelorLogin"/>
  <testcase name="LoginFailure" time="0.0" classname="webLogin.TeacherLogin"/>
  <testcase name="LoginSuccess" time="0.001" classname="webLogin.TeacherLogin"/>
  <testcase name="LoginFailure" time="0.001" classname="webLogin.ParentLogin"/>
  <testcase name="LoginSuccess" time="0.001" classname="webLogin.ParentLogin"/>
  <testcase name="LoginFailure" time="0.0" classname="webLogin.AdminLogin"/>
  <testcase name="LoginSuccess" time="0.001" classname="webLogin.AdminLogin"/>
  <testcase name="LoginFacebookFailure" time="0.001" classname="webLogin.StudentLogin"/>
  <testcase name="LoginFacebookSuccess" time="0.001" classname="webLogin.StudentLogin"/>
  <testcase name="LoginFailure" time="0.003" classname="webLogin.StudentLogin">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at webLogin.StudentLogin.LoginFailure(StudentLogin.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- LoginFailure -->
  <testcase name="LoginSuccess" time="0.001" classname="webLogin.StudentLogin"/>
  <testcase name="LoginTwitterFailure" time="0.001" classname="webLogin.StudentLogin"/>
  <testcase name="LoginTwitterSuccess" time="0.0" classname="webLogin.StudentLogin"/>
</testsuite> <!-- Default test -->
