<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="14" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="60" started-at="2018-01-19T17:43:51Z" finished-at="2018-01-19T17:43:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="60" started-at="2018-01-19T17:43:51Z" finished-at="2018-01-19T17:43:51Z">
      <class name="webLogin.CouncelorLogin">
        <test-method status="PASS" signature="LoginFailure()[pri:0, instance:webLogin.CouncelorLogin@5f341870]" name="LoginFailure" duration-ms="9" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailure -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:webLogin.CouncelorLogin@5f341870]" name="LoginSuccess" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
      </class> <!-- webLogin.CouncelorLogin -->
      <class name="webLogin.TeacherLogin">
        <test-method status="PASS" signature="LoginFailure()[pri:0, instance:webLogin.TeacherLogin@6500df86]" name="LoginFailure" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailure -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:webLogin.TeacherLogin@6500df86]" name="LoginSuccess" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
      </class> <!-- webLogin.TeacherLogin -->
      <class name="webLogin.ParentLogin">
        <test-method status="PASS" signature="LoginFailure()[pri:0, instance:webLogin.ParentLogin@589838eb]" name="LoginFailure" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailure -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:webLogin.ParentLogin@589838eb]" name="LoginSuccess" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
      </class> <!-- webLogin.ParentLogin -->
      <class name="webLogin.AdminLogin">
        <test-method status="PASS" signature="LoginFailure()[pri:0, instance:webLogin.AdminLogin@42dafa95]" name="LoginFailure" duration-ms="0" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailure -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:webLogin.AdminLogin@42dafa95]" name="LoginSuccess" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
      </class> <!-- webLogin.AdminLogin -->
      <class name="webLogin.StudentLogin">
        <test-method status="PASS" signature="LoginFacebookFailure()[pri:0, instance:webLogin.StudentLogin@271053e1]" name="LoginFacebookFailure" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFacebookFailure -->
        <test-method status="PASS" signature="LoginFacebookSuccess()[pri:0, instance:webLogin.StudentLogin@271053e1]" name="LoginFacebookSuccess" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFacebookSuccess -->
        <test-method status="FAIL" signature="LoginFailure()[pri:0, instance:webLogin.StudentLogin@271053e1]" name="LoginFailure" duration-ms="3" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at webLogin.StudentLogin.LoginFailure(StudentLogin.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailure -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:webLogin.StudentLogin@271053e1]" name="LoginSuccess" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
        <test-method status="PASS" signature="LoginTwitterFailure()[pri:0, instance:webLogin.StudentLogin@271053e1]" name="LoginTwitterFailure" duration-ms="1" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTwitterFailure -->
        <test-method status="PASS" signature="LoginTwitterSuccess()[pri:0, instance:webLogin.StudentLogin@271053e1]" name="LoginTwitterSuccess" duration-ms="0" started-at="2018-01-19T12:43:51Z" finished-at="2018-01-19T12:43:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTwitterSuccess -->
      </class> <!-- webLogin.StudentLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
